"""Generation seed derivation that does not depend on output column name.

R3.10 locks the V1 contract: same generation key + same strategy/config
must produce the same generated bytes regardless of the display column
name. The previous ``derive_key("col:<column_name>")`` path coupled
output to a UI-mutable string; renaming a column rebuilt generation,
and two columns sharing identical config but different display names
silently produced different output. Both behaviors broke the V1
"reproduce on rebuild" promise.

This module exposes:

    strategy_config_fingerprint(column_config) -> str
        Stable hex digest of the parts of column_config that actually
        affect output (strategy type + strategy-specific knobs, excluding
        display name and null probability). Used both as the seed-info
        label fed to derive_key() and as the value snapshotted into the
        evidence manifest so verifiers can prove "same fingerprint =>
        same generation contract".

    synthetic_column_seed(derive_key, column_config, fallback_seed) -> int
        Per-column base seed for synthetic generation. Keyed path:
        derive_key("gen:" + fingerprint)[:4] as a 32-bit int. Unkeyed
        fallback: fallback_seed XOR a digest of the fingerprint. Honors
        ``determinism: fresh`` via os.urandom for the admin-allowed
        roll-per-run path.

The single-byte XOR fallback uses the fingerprint, not the column name,
so a rename never shifts the generated bytes even when no master key is
configured.
"""

from __future__ import annotations

import hashlib
import json
import os
from collections.abc import Callable
from typing import Any

# Fields that are intentionally excluded from the fingerprint. ``name``
# is the rename surface R3.10 is severing. ``null_probability`` is a
# post-generation filter that doesn't change the underlying value the
# generator emits for a given row. ``determinism`` flips between stable
# and fresh paths but the *config* itself is the same set of inputs;
# determinism is recorded as a separate evidence field.
_EXCLUDED_FROM_FINGERPRINT = frozenset(
    {
        "name",
        "null_probability",
        "determinism",
        "_legacy_column_name_seed",
    }
)


def strategy_config_fingerprint(column_config: dict[str, Any]) -> str:
    """SHA-256 hex of canonical JSON of the strategy-relevant config.

    Canonical JSON: sorted keys, no whitespace, default ``ensure_ascii``
    so the bytes are identical regardless of locale or Python build.
    Returns the full 64-char hex; callers that want a shorter label can
    truncate.
    """
    payload = {
        k: v for k, v in (column_config or {}).items() if k not in _EXCLUDED_FROM_FINGERPRINT
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _bytes_to_seed(b: bytes) -> int:
    """First 4 bytes as a non-negative 32-bit int."""
    return int.from_bytes(b[:4], "big", signed=False)


def synthetic_column_seed(
    derive_key: Callable[[str], bytes] | None,
    column_config: dict[str, Any],
    fallback_seed: int,
) -> int:
    """Per-column base seed for synthetic generators.

    Resolution order:

    1. ``column_config["determinism"] == "fresh"`` -> draw a new seed
       from ``os.urandom``. Same seed for every row in the column so
       within-run consistency holds (a formula referencing this column
       sees a stable value), but different seed each run so the column's
       output rolls. This path is admin-gated upstream by
       ``allow_per_pipeline_random_generation``; the engine accepts
       whatever the platform/CLI passes in.

    2. ``derive_key`` set -> ``derive_key("gen:" + fingerprint)[:4]``.
       Pipeline-key-scoped, not column-name-scoped. Same key + same
       config always yields the same bytes; renaming the column does
       not affect output.

    3. ``column_config.get("_legacy_column_name_seed")`` truthy -> route
       through ``derive_key("col:<name>")`` so direct-YAML pipelines that
       relied on the pre-R3.10 contract can opt back in. Web UI never
       sets this; it's documented compat surface for legacy CLI runs.

    4. Unkeyed fallback -> ``fallback_seed XOR md5(fingerprint)[:4]``.
       Reproducible without any master key but still independent of the
       column display name.
    """
    if column_config is not None and column_config.get("determinism") == "fresh":
        return _bytes_to_seed(os.urandom(4))

    if (
        derive_key is not None
        and column_config is not None
        and column_config.get("_legacy_column_name_seed")
    ):
        try:
            return _bytes_to_seed(derive_key(f"col:{column_config.get('name', 'unnamed')}"))
        except Exception:
            pass  # fall through to fingerprint-based path

    fingerprint = strategy_config_fingerprint(column_config or {})

    if derive_key is not None:
        try:
            return _bytes_to_seed(derive_key(f"gen:{fingerprint}"))
        except Exception:
            pass

    # Non-crypto use: MD5 is just a fast deterministic 16-byte digest
    # mixed into the fallback seed for reproducibility across runs.
    # Cryptographic strength is not a requirement here.
    digest = hashlib.md5(fingerprint.encode("utf-8")).digest()  # noqa: S324
    name_int = _bytes_to_seed(digest)
    return (int(fallback_seed) ^ name_int) & 0x7FFFFFFF
