"""Generation seed derivation that does not depend on output column name.

R3.10 locks the V1 contract: same generation key + same strategy/config
must produce the same generated bytes regardless of the display column
name. The previous ``derive_key("col:<column_name>")`` path coupled
output to a UI-mutable string; renaming a column rebuilt generation,
and two columns sharing identical config but different display names
silently produced different output. Both behaviors broke the V1
"reproduce on rebuild" promise.

This module exposes:

    strategy_config_fingerprint(column_config) -> str
        Stable hex digest of the parts of column_config that actually
        affect output (strategy type + strategy-specific knobs, excluding
        display name and null probability). Used both as the seed-info
        label fed to derive_key() and as the value snapshotted into the
        evidence manifest so verifiers can prove "same fingerprint =>
        same generation contract".

    GenDeriveContext.for_column(derive_key, column_config, fallback_seed)
        Per-column generation derivation (F2/F3, v6). Resolves one 32-byte
        column root (keyed path: full derive_key("gen:" + fingerprint), no
        longer truncated to 4 bytes), then exposes disjoint per-RNG-family
        and per-row sub-derivations. Honors ``determinism: fresh`` via
        os.urandom and the ``_legacy_column_name_seed`` opt-in.

The fallback path uses the fingerprint, not the column name, so a rename
never shifts the generated bytes even when no master key is configured.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
from collections.abc import Callable
from typing import Any

from decoy_engine.determinism import SEED_PROTOCOL_VERSION

# Fields that are intentionally excluded from the fingerprint. ``name``
# is the rename surface R3.10 is severing. ``null_probability`` is a
# post-generation filter that doesn't change the underlying value the
# generator emits for a given row. ``determinism`` flips between stable
# and fresh paths but the *config* itself is the same set of inputs;
# determinism is recorded as a separate evidence field.
_EXCLUDED_FROM_FINGERPRINT = frozenset(
    {
        "name",
        "null_probability",
        "determinism",
        "_legacy_column_name_seed",
    }
)

# ``snapshot_file`` (statistical columns) is a FILESYSTEM PATH, not a
# generation input. Hashing the path string couples the derived seed to a
# UI/ops-mutable location: renaming or date-stamping a snapshot silently
# shifts synthetic output, and a harness that stages the snapshot in a
# fresh temp dir per run gets a different seed every process (breaking the
# cross-process determinism gate). We substitute the path with the SHA-256
# of the file's CONTENT before fingerprinting, so the same distribution at
# ANY path yields the same seed, and two genuinely different snapshots
# yield different seeds. Excluding it outright (dropping it) would instead
# collide two different snapshots onto one seed -- the wrong direction.
_SNAPSHOT_FILE_KEY = "snapshot_file"


def _snapshot_content_digest(path: str) -> str:
    """SHA-256 hex of a snapshot file's raw bytes, for use in the fingerprint.

    Content, not path: the same snapshot at any location fingerprints
    identically. Raises RuntimeError (fail loud) when the file is missing
    or unreadable rather than silently falling back to the path string,
    which would reintroduce the path-coupling bug.
    """
    try:
        with open(path, "rb") as fh:
            data = fh.read()
    except OSError as exc:
        raise RuntimeError(
            f"strategy_config_fingerprint: snapshot_file {path!r} is missing or "
            f"unreadable ({type(exc).__name__}: {exc}); cannot derive a stable "
            f"content-based seed. Fix the path or file rather than falling back "
            f"to the path string (which would silently change synthetic output)."
        ) from exc
    return "sha256:" + hashlib.sha256(data).hexdigest()


def strategy_config_fingerprint(column_config: dict[str, Any]) -> str:
    """SHA-256 hex of canonical JSON of the strategy-relevant config.

    Canonical JSON: sorted keys, no whitespace, default ``ensure_ascii``
    so the bytes are identical regardless of locale or Python build.
    Returns the full 64-char hex; callers that want a shorter label can
    truncate.

    ``snapshot_file`` is fingerprinted by CONTENT, not path (see
    ``_SNAPSHOT_FILE_KEY``): its value in the payload is replaced with the
    SHA-256 of the referenced file's bytes so the seed follows the
    distribution, not the filesystem location.
    """
    payload = {
        k: v for k, v in (column_config or {}).items() if k not in _EXCLUDED_FROM_FINGERPRINT
    }
    snapshot_file = payload.get(_SNAPSHOT_FILE_KEY)
    if snapshot_file:
        payload[_SNAPSHOT_FILE_KEY] = _snapshot_content_digest(str(snapshot_file))
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# RNG families a generated column may drive. Each gets a disjoint sub-key so
# the three never share one int (F3) and adjacent columns never correlate.
#   py    -> random.Random(...)
#   np    -> numpy.random.default_rng(...)
#   faker -> Faker.seed_instance(...)
GEN_FAMILIES = ("py", "np", "faker")


def _gen_hmac(key: bytes, label: bytes, *, extra: bytes = b"") -> bytes:
    """Version-mixed, length-prefixed HMAC-SHA256.

    Mirrors `determinism._derive.derive_source` byte-for-byte in shape:
    `version_byte || len(label) || label || len(extra) || extra`. Mixing
    SEED_PROTOCOL_VERSION makes generation output version-aware (the same
    way the mask path is), so the protocol version is the single
    compatibility knob and a cross-version vaulted-unmask can detect drift.
    """
    hmac_input = (
        bytes([SEED_PROTOCOL_VERSION])
        + len(label).to_bytes(4, "big")
        + label
        + len(extra).to_bytes(4, "big")
        + extra
    )
    return hmac.new(key, hmac_input, hashlib.sha256).digest()


class GenDeriveContext:
    """Per-column generation derivation: full-32-byte, per-family, per-row.

    Replaces the F2 4-byte truncation (`_bytes_to_seed`) and the F3
    `column_seed + i` arithmetic. One 32-byte column root is resolved once
    (see `for_column`); per-family keys and per-row ints are derived from it
    by HMAC, mirroring `determinism._derive.DeriveContext` (precompute key
    once, cheap per-row HMAC). Distinct labels give independent HKDF/HMAC
    outputs, so:

    - the three RNG families (`GEN_FAMILIES`) no longer share one int, and
    - adjacent columns (distinct fingerprints -> distinct roots) no longer
      produce row-shifted-identical streams.

    `base_int(family)` seeds base-only consumers (`random.Random`,
    `numpy.default_rng`) with full-width material. `row_int(family, i)`
    replaces the per-row `seed + i` for faker/formula row loops.
    """

    __slots__ = ("_family_keys", "_root")

    def __init__(self, root: bytes) -> None:
        self._root = root
        self._family_keys: dict[str, bytes] = {}

    @classmethod
    def for_column(
        cls,
        derive_key: Callable[[str], bytes] | None,
        column_config: dict[str, Any],
        fallback_seed: int,
    ) -> GenDeriveContext:
        """Resolve the 32-byte column root, preserving the four-path order of
        the legacy `synthetic_column_seed` (fresh / legacy / keyed / unkeyed).

        Keyed path uses the SAME `derive_key("gen:" + fingerprint)` label as
        before (now consuming all 32 bytes, not the first 4). Raises on a
        `derive_key` resolver failure (QA-1 M18 contract) rather than
        silently degrading to the unkeyed path.
        """
        cfg = column_config or {}

        if cfg.get("determinism") == "fresh":
            # Same root for every row this run (within-run stable), fresh
            # across runs. Full 32 bytes, not 4.
            return cls(os.urandom(32))

        if derive_key is not None and cfg.get("_legacy_column_name_seed"):
            name = cfg.get("name", "unnamed")
            try:
                root = derive_key(f"col:{name}")
            except Exception as exc:
                raise RuntimeError(
                    f"GenDeriveContext: derive_key failed for legacy "
                    f"column-name path (column={name!r}): {type(exc).__name__}"
                ) from exc
            return cls(root)

        fingerprint = strategy_config_fingerprint(cfg)

        if derive_key is not None:
            try:
                root = derive_key(f"gen:{fingerprint}")
            except Exception as exc:
                raise RuntimeError(
                    f"GenDeriveContext: derive_key failed for fingerprint-based "
                    f"path (fingerprint={fingerprint!r}): {type(exc).__name__}"
                ) from exc
            return cls(root)

        # Unkeyed fallback: HKDF-strength root over the fallback seed +
        # fingerprint (replaces the old md5[:4] truncation). Reproducible
        # without a master key, still independent of the column display name.
        # fallback_seed is expected in [0, 2**64): the plan path normalizes it
        # via _normalize_job_seed_int before generation. A direct-API caller
        # passing a negative or oversized seed fails loud here (OverflowError)
        # rather than silently masking it the way the old `& 0x7FFFFFFF` did.
        digest = hashlib.sha256(
            int(fallback_seed).to_bytes(8, "big", signed=False) + fingerprint.encode("utf-8")
        ).digest()
        return cls(digest)

    def _family_key(self, family: str) -> bytes:
        key = self._family_keys.get(family)
        if key is None:
            key = _gen_hmac(self._root, b"fam:" + family.encode("utf-8"))
            self._family_keys[family] = key
        return key

    def base_int(self, family: str) -> int:
        """Full-width non-negative int for a base-only RNG seed (one per column)."""
        return int.from_bytes(self._family_key(family), "big", signed=False)

    def row_int(self, family: str, i: int) -> int:
        """Full-width non-negative int for row `i` of `family` (replaces seed + i)."""
        block = _gen_hmac(
            self._family_key(family), family.encode("utf-8"), extra=i.to_bytes(8, "big")
        )
        return int.from_bytes(block, "big", signed=False)
