"""Property + metamorphic invariants for HKDF-SHA256 key derivation.

TQ crown-jewels pass (Test-Quality Program) on `determinism/_hkdf.py`, a
crypto crown jewel held to the mandatory 100% mutation bar (see
`docs/quality/module-test-quality-playbook.md`). The existing
`tests/unit/determinism/test_hkdf.py` suite is a differential oracle: three
RFC 5869 appendix test vectors plus two hand-picked boundary examples. That
suite proves the implementation matches the published reference for a
handful of FIXED inputs; it says nothing about the general contract the
module claims for itself over the whole input domain. These tests are that
general contract, expressed as properties Hypothesis searches for a
counterexample against.

The invariants come from `_hkdf.py`'s own docstrings and RFC 5869
(https://datatracker.ietf.org/doc/html/rfc5869):

- DETERMINISM: `hkdf_extract`, `hkdf_expand`, and `hkdf_sha256` are pure
  functions -- equal inputs produce an equal output, every call. The
  determinism layer that calls this module depends on this to reproduce a
  given namespace's key across processes and re-runs.
- DOMAIN SEPARATION: RFC 5869 section 3.2's whole point is that varying
  `info` (or `salt`, or the input key material) must decorrelate the derived
  key from any other context's key. A collision here would mean two
  logically separate namespaces could end up sharing key material.
- OUTPUT LENGTH: `hkdf_expand`'s docstring contracts the output to be
  exactly `length` bytes for `0 <= length <= 255 * 32` (RFC 5869 section
  2.3's `dkLen <= 255 * HashLen` bound); above that bound it raises
  `ValueError` rather than silently truncating or wrapping.
- EXTRACT OUTPUT SIZE: `hkdf_extract`'s PRK is always exactly one SHA-256
  digest (32 bytes), independent of `salt` or `ikm` size (RFC 5869 section
  2.2).
- PREFIX PROPERTY: RFC 5869 section 2.3 builds `OKM` as a truncation of the
  concatenated block sequence `T(1) | T(2) | ...`, and each `T(i)` depends
  only on `PRK`, `info`, and its own index -- never on the REQUESTED length.
  So a shorter expansion is always a byte-for-byte PREFIX of a longer one
  derived from the same `(prk, info)`. A mutant that recomputed blocks from
  the requested length (instead of the running index) would still pass every
  single-length example test yet fail this metamorphic relation.
- COMPOSITION: `hkdf_sha256`'s docstring states it is "Equivalent to
  `hkdf_expand(hkdf_extract(salt, ikm), info, length)`" -- the one-shot path
  and the explicit two-step path must never diverge.
- EMPTY-SALT REJECTION: QA-10 F12 (2026-06-01, cited in `hkdf_extract`'s
  docstring) rejects an empty salt so a quietly-failed salt-generation step
  cannot silently degrade to the RFC's weaker all-zero fallback.

Run:  pytest tests/property/test_hkdf_invariants.py -q
"""

from __future__ import annotations

import pytest
from hypothesis import assume, example, given, settings
from hypothesis import strategies as st

from decoy_engine.determinism._hkdf import hkdf_expand, hkdf_extract, hkdf_sha256

# Match the pilot's audit profile (tests/property/test_ri_graph_invariants.py):
# more examples than the 100-example default, no deadline, print_blob so any
# counterexample is replayable outside the interactive run.
settings.register_profile(
    "audit",
    max_examples=300,
    deadline=None,
    print_blob=True,
)
settings.load_profile("audit")

_HASH_LEN = 32  # SHA-256 digest length in bytes (RFC 5869 section 2)
_MAX_LENGTH = 255 * _HASH_LEN  # RFC 5869 section 2.3: dkLen <= 255 * HashLen

# Keep generated byte strings small: HMAC-SHA256 cost is linear in message
# size and `hkdf_expand` already loops up to 255 times per call near the
# length boundary, so bounding salt/ikm/info size keeps 300 examples fast
# without narrowing the domain in any way that matters to these invariants
# (HMAC's behavior does not change qualitatively with input size).
_bytes = st.binary(max_size=64)
_nonempty_bytes = st.binary(min_size=1, max_size=64)
_length = st.integers(min_value=0, max_value=_MAX_LENGTH)
# Domain-separation properties ("different input -> different output") hold only
# up to a hash collision. At a 1-byte OKM two distinct inputs collide ~1/256 of
# the time, so those properties draw a wide length (>= 16 bytes => collision
# ~1/2**128, cryptographically negligible). Determinism/length properties keep
# the full range.
_wide_length = st.integers(min_value=16, max_value=_MAX_LENGTH)
_length_over_max = st.integers(min_value=_MAX_LENGTH + 1, max_value=_MAX_LENGTH + 10_000)


# --------------------------------------------------------------------------
# Determinism
# --------------------------------------------------------------------------


@given(salt=_nonempty_bytes, ikm=_bytes)
def test_hkdf_extract_is_deterministic(salt: bytes, ikm: bytes) -> None:
    """Equal (salt, ikm) produces an equal PRK, every call (pure function)."""
    assert hkdf_extract(salt, ikm) == hkdf_extract(salt, ikm)


@given(prk=_bytes, info=_bytes, length=_length)
def test_hkdf_expand_is_deterministic(prk: bytes, info: bytes, length: int) -> None:
    """Equal (prk, info, length) produces an equal OKM, every call."""
    assert hkdf_expand(prk, info, length) == hkdf_expand(prk, info, length)


@given(ikm=_bytes, salt=_nonempty_bytes, info=_bytes, length=_length)
def test_hkdf_sha256_is_deterministic(ikm: bytes, salt: bytes, info: bytes, length: int) -> None:
    """The one-shot path is deterministic too: identical (key material,
    salt, info, length) inputs produce identical output bytes, every time.
    This is the guarantee the determinism layer relies on to reproduce a
    namespace's key across separate processes and re-runs."""
    first = hkdf_sha256(ikm, salt, info, length)
    second = hkdf_sha256(ikm, salt, info, length)
    assert first == second


# --------------------------------------------------------------------------
# Domain separation (RFC 5869 section 3.2)
# --------------------------------------------------------------------------


@given(salt1=_nonempty_bytes, salt2=_nonempty_bytes, ikm=_bytes)
def test_extract_domain_separation_by_salt(salt1: bytes, salt2: bytes, ikm: bytes) -> None:
    """A different `salt`, all else equal, must not collide on the PRK."""
    assume(salt1 != salt2)
    assert hkdf_extract(salt1, ikm) != hkdf_extract(salt2, ikm)


@given(ikm1=_bytes, ikm2=_bytes, salt=_nonempty_bytes)
def test_extract_domain_separation_by_ikm(ikm1: bytes, ikm2: bytes, salt: bytes) -> None:
    """A different `ikm` (input key material), all else equal, must not
    collide on the PRK."""
    assume(ikm1 != ikm2)
    assert hkdf_extract(salt, ikm1) != hkdf_extract(salt, ikm2)


@given(prk=_nonempty_bytes, info1=_bytes, info2=_bytes, length=_wide_length)
def test_expand_domain_separation_by_info(prk: bytes, info1: bytes, info2: bytes, length: int) -> None:
    """A different `info`, all else equal, must not collide on the OKM."""
    assume(info1 != info2)
    assert hkdf_expand(prk, info1, length) != hkdf_expand(prk, info2, length)


@given(ikm=_bytes, salt=_nonempty_bytes, info1=_bytes, info2=_bytes, length=_wide_length)
def test_sha256_domain_separation_by_info(ikm: bytes, salt: bytes, info1: bytes, info2: bytes, length: int) -> None:
    """End-to-end: changing `info` alone must yield a different derived key
    (no collision across domains)."""
    assume(info1 != info2)
    assert hkdf_sha256(ikm, salt, info1, length) != hkdf_sha256(ikm, salt, info2, length)


@given(ikm=_bytes, salt1=_nonempty_bytes, salt2=_nonempty_bytes, info=_bytes, length=_wide_length)
def test_sha256_domain_separation_by_salt(ikm: bytes, salt1: bytes, salt2: bytes, info: bytes, length: int) -> None:
    """End-to-end: changing `salt` alone must yield a different derived
    key."""
    assume(salt1 != salt2)
    assert hkdf_sha256(ikm, salt1, info, length) != hkdf_sha256(ikm, salt2, info, length)


@given(ikm1=_bytes, ikm2=_bytes, salt=_nonempty_bytes, info=_bytes, length=_wide_length)
def test_sha256_domain_separation_by_ikm(ikm1: bytes, ikm2: bytes, salt: bytes, info: bytes, length: int) -> None:
    """End-to-end: changing the input key material alone must yield a
    different derived key."""
    assume(ikm1 != ikm2)
    assert hkdf_sha256(ikm1, salt, info, length) != hkdf_sha256(ikm2, salt, info, length)


# --------------------------------------------------------------------------
# Output length (RFC 5869 section 2.3 bound) and the extract PRK size
# --------------------------------------------------------------------------


@given(salt=_nonempty_bytes, ikm=_bytes)
def test_extract_output_is_always_hash_len_bytes(salt: bytes, ikm: bytes) -> None:
    """`hkdf_extract`'s PRK is exactly one SHA-256 digest (32 bytes),
    regardless of `salt` or `ikm` size (RFC 5869 section 2.2)."""
    assert len(hkdf_extract(salt, ikm)) == _HASH_LEN


@example(prk=b"\x00" * 32, info=b"", length=0)
@example(prk=b"\x00" * 32, info=b"", length=1)
@example(prk=b"\x00" * 32, info=b"", length=32)
@example(prk=b"\x00" * 32, info=b"", length=_MAX_LENGTH)
@given(prk=_bytes, info=_bytes, length=_length)
def test_expand_output_length_matches_request(prk: bytes, info: bytes, length: int) -> None:
    """The derived output is exactly the requested length, over the whole
    valid range, with the boundaries pinned explicitly: 0 (the loop body
    never runs), 1 and 32 (below and at one hash block), and the RFC 5869
    maximum (`255 * HashLen`, the last valid block count)."""
    assert len(hkdf_expand(prk, info, length)) == length


@given(prk=_bytes, info=_bytes, length=_length_over_max)
def test_expand_rejects_length_over_max(prk: bytes, info: bytes, length: int) -> None:
    """RFC 5869 section 2.3: `dkLen` above `255 * HashLen` has no defined
    expansion and must raise, not silently truncate or wrap."""
    with pytest.raises(ValueError, match=f"exceeds RFC 5869 maximum {_MAX_LENGTH}"):
        hkdf_expand(prk, info, length)


# --------------------------------------------------------------------------
# Metamorphic: prefix property and one-shot/two-step composition
# --------------------------------------------------------------------------


@given(prk=_bytes, info=_bytes, l1=_length, l2=_length)
def test_expand_output_is_prefix_of_longer_expansion(prk: bytes, info: bytes, l1: int, l2: int) -> None:
    """RFC 5869 section 2.3: each `T(i)` block depends only on `(prk, info,
    i)`, never on the caller's requested length, so the shorter of two
    expansions from the same `(prk, info)` is always a byte-for-byte prefix
    of the longer one. A mutant that let the requested length leak into the
    per-block computation would still satisfy `test_expand_output_length_
    matches_request` in isolation but fail this relation."""
    lo, hi = sorted((l1, l2))
    short = hkdf_expand(prk, info, lo)
    long_ = hkdf_expand(prk, info, hi)
    assert long_[:lo] == short


@given(ikm=_bytes, salt=_nonempty_bytes, info=_bytes, length=_length)
def test_sha256_equals_manual_extract_then_expand(ikm: bytes, salt: bytes, info: bytes, length: int) -> None:
    """`hkdf_sha256`'s own docstring: "Equivalent to `hkdf_expand(hkdf_
    extract(salt, ikm), info, length)`". The one-shot path and the explicit
    two-step path must never diverge."""
    prk = hkdf_extract(salt, ikm)
    assert hkdf_sha256(ikm, salt, info, length) == hkdf_expand(prk, info, length)


# --------------------------------------------------------------------------
# Empty-salt rejection (QA-10 F12), generalized over `ikm`
# --------------------------------------------------------------------------


@given(ikm=_bytes)
def test_extract_rejects_empty_salt_for_any_ikm(ikm: bytes) -> None:
    """QA-10 F12 (2026-06-01): a quietly-failed salt-generation step must
    not silently degrade to the RFC's weaker all-zero fallback, for ANY
    `ikm` -- not just the one fixed vector the example-based unit test
    covers."""
    with pytest.raises(ValueError, match="salt must be non-empty"):
        hkdf_extract(b"", ikm)
