"""Pins the shared derive_index KAT fixture against the live Python reference.

Phase 2 Task 2.1 freezes the deterministic-Faker pool-selection contract. The fixture
`decoy-engine-native/vectors/derive_index_kat.json` (generated by
`vectors/generate_derive_index_kat.py`) is the cross-language known-answer set that the
eventual compiled `derive_index_batch` (Task 2.2) must reproduce index-for-index. This
test proves the fixture is faithful to the shipped `derive_index` + `_canonicalize_source`
right now, so a later Rust mismatch is a Rust bug, not a stale fixture. The pure-Python checks
run in the ordinary suite; the companion-present tests exercise the compiled derive_index_batch
against the same fixture + a live differential.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from typing import Any

import pytest

from decoy_engine.determinism import DeterminismError, derive_index
from decoy_engine.generation.pool._canonicalize import _canonicalize_source

_COMPANION_PRESENT = importlib.util.find_spec("decoy_engine_native") is not None
_NEEDS_COMPANION = pytest.mark.skipif(
    not _COMPANION_PRESENT,
    reason="decoy-engine-native companion not installed; the companion-present CI job covers this",
)

_FIXTURE_PATH = (
    Path(__file__).resolve().parents[2]
    / "decoy-engine-native"
    / "vectors"
    / "derive_index_kat.json"
)


def _fixture() -> dict[str, Any]:
    return json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))


def _canonical_from_hex(hex_or_none: str | None) -> bytes | None:
    return None if hex_or_none is None else bytes.fromhex(hex_or_none)


def _build_case_array(case: dict[str, Any]) -> Any:
    """Reconstruct the exact pyarrow Array a fixture value case describes (same construction as
    the generator: logical values -> native -> pa.array with the pinned arrow type)."""
    import pandas as pd
    import pyarrow as pa

    at = case["arrow_type"]
    kind = at["kind"]
    if kind == "utf8":
        dtype = pa.string()
    elif kind == "large_utf8":
        dtype = pa.large_string()
    elif kind == "bool":
        dtype = pa.bool_()
    elif kind == "int":
        widths = {
            (8, True): pa.int8(),
            (8, False): pa.uint8(),
            (16, True): pa.int16(),
            (16, False): pa.uint16(),
            (32, True): pa.int32(),
            (32, False): pa.uint32(),
            (64, True): pa.int64(),
            (64, False): pa.uint64(),
        }
        dtype = widths[(at["bits"], at["signed"])]
    elif kind == "timestamp":
        dtype = pa.timestamp(at["unit"], tz=at["tz"])
    else:  # pragma: no cover - fixture only carries admitted kinds
        raise AssertionError(f"unhandled kind {kind!r}")

    def _to_native(value: Any) -> Any:
        if value is None:
            return None
        if kind == "int":
            return int(value)
        if kind == "timestamp":
            return pd.Timestamp(value)
        return value

    return pa.array([_to_native(v) for v in case["logical_values"]], type=dtype)


_CASES = _fixture()["cases"]
_ERROR_CASES = _fixture()["error_cases"]


def test_fixture_seed_protocol_version_matches_the_live_constant() -> None:
    """The fixture header pins the seed_protocol_version its indices were generated under. If the
    live constant is bumped, the expected indices are stale and the fixture must be regenerated;
    this fails loudly at that point instead of trusting the numbers silently."""
    from decoy_engine.determinism._derive import SEED_PROTOCOL_VERSION

    assert _fixture()["seed_protocol_version"] == SEED_PROTOCOL_VERSION, (
        "derive_index_kat.json was generated under a different SEED_PROTOCOL_VERSION; regenerate it "
        "with vectors/generate_derive_index_kat.py"
    )


@pytest.mark.parametrize("case", _CASES, ids=[c["name"] for c in _CASES])
def test_derive_index_reproduces_every_kat_index(case: dict[str, Any]) -> None:
    """Every non-null row's derived index must equal the frozen expected index, computed
    from the canonical bytes the fixture also pins. Null rows carry a null index and are
    never derived (the sampler's null-in -> null-out contract)."""
    seed = bytes.fromhex(case["seed_hex"])
    namespace = case["namespace"]
    pool_size = case["pool_size"]

    for canonical_hex, expected_index in zip(
        case["expected_canonical_source_hex"], case["expected_index"], strict=True
    ):
        if expected_index is None:
            assert canonical_hex is None, "a null index must pair with a null canonical source"
            continue
        canonical = _canonical_from_hex(canonical_hex)
        assert canonical is not None
        got = derive_index(seed, namespace, canonical, pool_size=pool_size)
        assert got == expected_index, (
            f"{case['name']}: index drift for canonical {canonical_hex}: "
            f"expected {expected_index}, got {got}"
        )
        assert 0 <= got < pool_size


def test_canonicalization_matches_the_pinned_bytes() -> None:
    """The canonical source bytes the fixture pins must match what the live
    `_canonicalize_source` produces for the same logical values, so the index contract
    is anchored to a stable canonicalization, not just stable digests."""
    for case in _CASES:
        array = _build_case_array(case)
        for value, expected_hex in zip(
            array.to_pylist(), case["expected_canonical_source_hex"], strict=True
        ):
            if value is None:
                assert expected_hex is None
                continue
            assert _canonicalize_source(value).hex() == expected_hex, (
                f"{case['name']}: canonicalization drift for logical value {value!r}"
            )


@pytest.mark.parametrize("case", _ERROR_CASES, ids=[c["name"] for c in _ERROR_CASES])
def test_derive_index_error_cases_raise_the_pinned_code(case: dict[str, Any]) -> None:
    """Pool-size and framing rejections must raise DeterminismError with the exact coded
    error the fixture pins, so a compiled port cannot silently accept or remap them."""
    seed = bytes.fromhex(case["seed_hex"])
    source = bytes.fromhex(case["source_hex"])
    with pytest.raises(DeterminismError) as exc:
        derive_index(seed, case["namespace"], source, pool_size=case["pool_size"])
    assert exc.value.code == case["expected_error_code"]


def test_index_is_partition_and_thread_invariant() -> None:
    """derive_index is a pure per-row function: an index depends only on its own
    (seed, namespace, source, pool_size), never on surrounding rows or call order. So the
    KAT's per-row expectations hold under any partitioning a batched/parallel port might
    use. Assert it directly: the fixture's rows in original vs reversed order derive the
    same per-row indices."""
    for case in _CASES:
        seed = bytes.fromhex(case["seed_hex"])
        namespace = case["namespace"]
        pool_size = case["pool_size"]
        pairs: list[tuple[bytes, int]] = [
            (bytes.fromhex(h), idx)
            for h, idx in zip(
                case["expected_canonical_source_hex"], case["expected_index"], strict=True
            )
            if idx is not None and h is not None
        ]
        forward = [derive_index(seed, namespace, c, pool_size=pool_size) for c, _ in pairs]
        reverse = [
            derive_index(seed, namespace, c, pool_size=pool_size) for c, _ in reversed(pairs)
        ]
        assert forward == [idx for _, idx in pairs]
        assert list(reversed(reverse)) == forward


@_NEEDS_COMPANION
@pytest.mark.parametrize("case", _CASES, ids=[c["name"] for c in _CASES])
def test_compiled_derive_index_batch_reproduces_the_kat(case: dict[str, Any]) -> None:
    """The compiled derive_index_batch must reproduce every frozen expected index per row (null in
    -> null out) through the real PyO3 boundary + kernel, at several thread counts."""
    import decoy_engine_native._kernel as kernel

    array = _build_case_array(case)
    seed = bytes.fromhex(case["seed_hex"])
    for threads in (1, 4):
        out = kernel.derive_index_batch(
            array,
            mask_key=seed,
            namespace=case["namespace"],
            pool_size=case["pool_size"],
            native_threads=threads,
        )
        assert out.type == __import__("pyarrow").uint64()
        assert out.to_pylist() == case["expected_index"], (
            f"{case['name']} threads={threads}: compiled index diverged from the frozen KAT"
        )


@_NEEDS_COMPANION
@pytest.mark.parametrize("case", _ERROR_CASES, ids=[c["name"] for c in _ERROR_CASES])
def test_compiled_derive_index_batch_error_cases(case: dict[str, Any]) -> None:
    """Pool-size / seed / namespace rejections must raise the pinned coded error from the compiled
    kernel too. Every error case uses the canonical "alice" source, so a one-row string array
    reproduces it."""
    import decoy_engine_native._kernel as kernel
    import pyarrow as pa

    assert bytes.fromhex(case["source_hex"]) == _canonicalize_source("alice")
    array = pa.array(["alice"], type=pa.string())
    seed = bytes.fromhex(case["seed_hex"])
    with pytest.raises(ValueError, match=case["expected_error_code"]):
        kernel.derive_index_batch(
            array,
            mask_key=seed,
            namespace=case["namespace"],
            pool_size=case["pool_size"],
            native_threads=1,
        )


@_NEEDS_COMPANION
@pytest.mark.parametrize("native_threads", [1, 2, 4, 8], ids=lambda t: f"threads_{t}")
def test_compiled_matches_live_python_over_random_inputs(native_threads: int) -> None:
    """Differential: the compiled derive_index_batch equals the shipped Python derive_index per
    non-null row over varied inputs, at every thread count."""
    import decoy_engine_native._kernel as kernel
    import pyarrow as pa

    seed = bytes(range(32))
    namespace = "pool.city"
    values = [None if i % 6 == 0 else f"user-{i}-{'z' * (i % 4)}" for i in range(500)]
    array = pa.array(values, type=pa.string())
    for pool_size in (1, 2, 97, 100003):
        out = kernel.derive_index_batch(
            array,
            mask_key=seed,
            namespace=namespace,
            pool_size=pool_size,
            native_threads=native_threads,
        ).to_pylist()
        for value, got in zip(values, out, strict=True):
            if value is None:
                assert got is None
                continue
            expected = derive_index(
                seed, namespace, _canonicalize_source(value), pool_size=pool_size
            )
            assert got == expected, f"pool={pool_size} value={value!r}: {got} != {expected}"


@_NEEDS_COMPANION
def test_compiled_non_integer_pool_size_is_ordered_after_canonicalization() -> None:
    """A non-int pool_size raises TypeError, but ONLY in the pool-guard slot: after the Arrow
    import and the first non-null row's canonicalization, and skipped entirely for a batch that
    validates nothing. So it must NOT short-circuit ahead of those, matching the reference (whose
    non-int rejection is the in-`derive_index` `pool_size > _POOL_SIZE_MAX` comparison, fired per
    non-null row after canonicalization, never for an all-null batch)."""
    import decoy_engine_native._kernel as kernel
    import pyarrow as pa

    seed = bytes(range(32))
    not_an_int = "not-an-int"

    # A clean first non-null row -> the non-int is rejected as TypeError (not a coded ValueError).
    clean = pa.array(["alice", "bob"], type=pa.string())
    with pytest.raises(TypeError):
        kernel.derive_index_batch(
            clean, mask_key=seed, namespace="ns", pool_size=not_an_int, native_threads=1
        )

    # A canon fault on the FIRST non-null row outranks the non-int pool: the canonicalization
    # ValueError wins, proving the non-int check did not fire ahead of the import + canon.
    bad_first = pa.array([2**63 - 1, 0], type=pa.timestamp("s", tz="UTC"))
    with pytest.raises(ValueError, match="mixed_object_not_native"):
        kernel.derive_index_batch(
            bad_first, mask_key=seed, namespace="ns", pool_size=not_an_int, native_threads=1
        )

    # All-null and empty batches validate NOTHING, so a non-int pool is tolerated (null/empty out).
    all_null = pa.array([None, None], type=pa.string())
    assert kernel.derive_index_batch(
        all_null, mask_key=seed, namespace="ns", pool_size=not_an_int, native_threads=1
    ).to_pylist() == [None, None]
    empty = pa.array([], type=pa.string())
    assert (
        kernel.derive_index_batch(
            empty, mask_key=seed, namespace="ns", pool_size=not_an_int, native_threads=1
        ).to_pylist()
        == []
    )


@_NEEDS_COMPANION
def test_panic_in_a_derive_index_worker_becomes_coded_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A panic inside a Rayon worker on the derive_index parallel fill must propagate out of the
    pool, unwind through the GIL-released region, and surface as the coded internal_panic error, not
    abort. Driven by DECOY_ENGINE_NATIVE_FORCE_PANIC_IN_WORKER (fires only on a pool worker);
    native_threads=2 over a 2-row batch forces two non-empty ranges."""
    import decoy_engine_native._kernel as kernel
    import pyarrow as pa

    values = pa.array(["a", "b"], type=pa.string())
    mask_key = b"\x44" * 32

    monkeypatch.setenv("DECOY_ENGINE_NATIVE_FORCE_PANIC_IN_WORKER", "1")
    with pytest.raises(ValueError, match="internal_panic"):
        kernel.derive_index_batch(
            values, mask_key=mask_key, namespace="pool.city", pool_size=1000, native_threads=2
        )

    # The GIL was restored and the pool is reusable: a clean call succeeds in the same process.
    monkeypatch.delenv("DECOY_ENGINE_NATIVE_FORCE_PANIC_IN_WORKER")
    out = kernel.derive_index_batch(
        values, mask_key=mask_key, namespace="pool.city", pool_size=1000, native_threads=2
    )
    assert len(out) == 2
