"""Pins the shared derive_index KAT fixture against the live Python reference.

Phase 2 Task 2.1 freezes the deterministic-Faker pool-selection contract. The fixture
`decoy-engine-native/vectors/derive_index_kat.json` (generated by
`vectors/generate_derive_index_kat.py`) is the cross-language known-answer set that the
eventual compiled `derive_index_batch` (Task 2.2) must reproduce index-for-index. This
test proves the fixture is faithful to the shipped `derive_index` + `_canonicalize_source`
right now, so a later Rust mismatch is a Rust bug, not a stale fixture. It is pure Python
(no compiled companion), so it runs in the ordinary suite as well as the native CI job.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from decoy_engine.determinism import DeterminismError, derive_index
from decoy_engine.generation.pool._canonicalize import _canonicalize_source

_FIXTURE_PATH = (
    Path(__file__).resolve().parents[2]
    / "decoy-engine-native"
    / "vectors"
    / "derive_index_kat.json"
)


def _fixture() -> dict[str, Any]:
    return json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))


def _canonical_from_hex(hex_or_none: str | None) -> bytes | None:
    return None if hex_or_none is None else bytes.fromhex(hex_or_none)


_CASES = _fixture()["cases"]
_ERROR_CASES = _fixture()["error_cases"]


@pytest.mark.parametrize("case", _CASES, ids=[c["name"] for c in _CASES])
def test_derive_index_reproduces_every_kat_index(case: dict[str, Any]) -> None:
    """Every non-null row's derived index must equal the frozen expected index, computed
    from the canonical bytes the fixture also pins. Null rows carry a null index and are
    never derived (the sampler's null-in -> null-out contract)."""
    seed = bytes.fromhex(case["seed_hex"])
    namespace = case["namespace"]
    pool_size = case["pool_size"]

    for canonical_hex, expected_index in zip(
        case["expected_canonical_source_hex"], case["expected_index"], strict=True
    ):
        if expected_index is None:
            assert canonical_hex is None, "a null index must pair with a null canonical source"
            continue
        canonical = _canonical_from_hex(canonical_hex)
        assert canonical is not None
        got = derive_index(seed, namespace, canonical, pool_size=pool_size)
        assert got == expected_index, (
            f"{case['name']}: index drift for canonical {canonical_hex}: "
            f"expected {expected_index}, got {got}"
        )
        assert 0 <= got < pool_size


def test_canonicalization_matches_the_pinned_bytes() -> None:
    """The canonical source bytes the fixture pins must match what the live
    `_canonicalize_source` produces for the same logical values, so the index contract
    is anchored to a stable canonicalization, not just stable digests."""
    import pandas as pd
    import pyarrow as pa

    def _to_native(kind: str, value: Any) -> Any:
        if value is None:
            return None
        if kind == "int":
            return int(value)
        if kind == "timestamp":
            return pd.Timestamp(value)
        return value

    for case in _CASES:
        at = case["arrow_type"]
        kind = at["kind"]
        if kind == "utf8":
            dtype = pa.string()
        elif kind == "large_utf8":
            dtype = pa.large_string()
        elif kind == "bool":
            dtype = pa.bool_()
        elif kind == "int":
            widths = {
                (8, True): pa.int8(),
                (8, False): pa.uint8(),
                (16, True): pa.int16(),
                (16, False): pa.uint16(),
                (32, True): pa.int32(),
                (32, False): pa.uint32(),
                (64, True): pa.int64(),
                (64, False): pa.uint64(),
            }
            dtype = widths[(at["bits"], at["signed"])]
        elif kind == "timestamp":
            dtype = pa.timestamp(at["unit"], tz=at["tz"])
        else:  # pragma: no cover - fixture only carries admitted kinds
            raise AssertionError(f"unhandled kind {kind!r}")

        array = pa.array([_to_native(kind, v) for v in case["logical_values"]], type=dtype)
        for value, expected_hex in zip(
            array.to_pylist(), case["expected_canonical_source_hex"], strict=True
        ):
            if value is None:
                assert expected_hex is None
                continue
            assert _canonicalize_source(value).hex() == expected_hex, (
                f"{case['name']}: canonicalization drift for logical value {value!r}"
            )


@pytest.mark.parametrize("case", _ERROR_CASES, ids=[c["name"] for c in _ERROR_CASES])
def test_derive_index_error_cases_raise_the_pinned_code(case: dict[str, Any]) -> None:
    """Pool-size and framing rejections must raise DeterminismError with the exact coded
    error the fixture pins, so a compiled port cannot silently accept or remap them."""
    seed = bytes.fromhex(case["seed_hex"])
    source = bytes.fromhex(case["source_hex"])
    with pytest.raises(DeterminismError) as exc:
        derive_index(seed, case["namespace"], source, pool_size=case["pool_size"])
    assert exc.value.code == case["expected_error_code"]


def test_index_is_partition_and_thread_invariant() -> None:
    """derive_index is a pure per-row function: an index depends only on its own
    (seed, namespace, source, pool_size), never on surrounding rows or call order. So the
    KAT's per-row expectations hold under any partitioning a batched/parallel port might
    use. Assert it directly: the fixture's rows in original vs reversed order derive the
    same per-row indices."""
    for case in _CASES:
        seed = bytes.fromhex(case["seed_hex"])
        namespace = case["namespace"]
        pool_size = case["pool_size"]
        pairs: list[tuple[bytes, int]] = [
            (bytes.fromhex(h), idx)
            for h, idx in zip(
                case["expected_canonical_source_hex"], case["expected_index"], strict=True
            )
            if idx is not None and h is not None
        ]
        forward = [derive_index(seed, namespace, c, pool_size=pool_size) for c, _ in pairs]
        reverse = [
            derive_index(seed, namespace, c, pool_size=pool_size) for c, _ in reversed(pairs)
        ]
        assert forward == [idx for _, idx in pairs]
        assert list(reversed(reverse)) == forward
