"""P4-A slice 1, acceptance test #5: bounded-parent split-dedup, measured RSS.

Companion proof to `tests/unit/execution/test_out_of_core_relation_split_dedup.py`'s
structural (EXPLAIN) and value-identity tests: this one measures REAL resident
memory in a fresh subprocess (VmHWM, allocator pinned -- same discipline as
`test_ooc_external_sort_memory.py`, whose docstring explains why VmHWM over
`ru_maxrss`), because only that proves the split's aggregate-then-join-back
shape stays bounded as distinct-key count grows, not just that it fits once.

Both the split form (winners `COPY`'d to disk, then a separate join-back that
reads them back) and the pre-split combined form (the winners aggregate as an
inline join subquery -- the ONE-query shape `_build_relation` replaced) are
reproduced here directly in SQL, deliberately bypassing `decoy_engine`'s own
per-batch Python staging loop: that loop's own row-by-row `to_pylist()` cost
would dominate the measured RSS at the row counts this proof needs, masking
the one thing under test (DuckDB's OWN operator memory). `staged.parquet` is
generated by a single vectorized DuckDB `COPY ... FROM generate_series(...)`
so the fixture-generation cost stays cheap and outside what is being measured.

FINDING (2026-09-02, load-bearing -- read before trusting this file's green):
on this box, DuckDB 1.5.4, the split's PLATEAU proof holds cleanly (see the
first assertion block below), but the NEGATIVE CONTROL specified by the plan
(`docs/plans/2026-09-02-p4a-bounded-parent-split-dedup.md` acceptance test #5)
-- that the pre-split combined form peaks >= 1.5x the split's peak at the same
K, OR raises a recognized OOM -- did NOT reproduce at any K/L this module's
author probed (500K..50M distinct keys, 64..1024 MiB limits, narrow and wide
per-group payloads, 1x-10x row/key duplication): the combined and split forms
tracked within a few percent of each other's peak RSS at every scale that
completed in bounded time, and where they diverged in success/failure, the
direction was inconsistent (one probe at K=20M/L=400MiB even had the SPLIT
form fail while combined succeeded). `EXPLAIN ANALYZE` on the combined form
shows DuckDB's optimizer pushing a dynamic min/max filter from the aggregate's
build side onto the join's probe-side `TABLE_SCAN`, which plausibly neutralizes
the co-residency penalty this shape would otherwise pay -- a query-planner
capability the plan's own measured numbers (cited in `_relation.py`'s WHY
comment) may predate. The negative control below is written to the letter of
the plan's spec, unweakened; it is expected to FAIL on this box as of this
finding. This is flagged to Cam/Codex for a decision (recalibrate the control,
scope it to a materially larger K on a bigger box, or accept the split purely
for its guaranteed-release architecture rather than a measured win here) --
not resolved unilaterally by loosening the assertion.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import textwrap

import pytest

pytestmark = pytest.mark.perf

# Allocator pinning, BEFORE the worker process starts -- same reasoning as
# `test_ooc_external_sort_memory.py`'s own `_CAPPED_ENV`.
_CAPPED_ENV = {
    "ARROW_DEFAULT_MEMORY_POOL": "system",
    "MALLOC_ARENA_MAX": "2",
}

# K chosen so the O(distinct-key) aggregate state is a small multiple of L
# (measured on this box: a 10M-group `max(int) GROUP BY` peaks ~1.3x L under a
# 350 MiB limit), while completing in single-digit seconds so the whole
# module -- three subprocess runs -- stays fast. 2K keeps the plateau check
# genuinely doubling the group count, not just re-running K.
_KEYS: int = 10_000_000
_LIMIT_MIB: int = 350
_DUPLICATE_RATIO: float = 1.05  # ~5% of keys get a second, later-row_nr row.

_ENVELOPE_FACTOR: float = 1.6
_PLATEAU_FACTOR: float = 1.15
_NEGATIVE_CONTROL_FACTOR: float = 1.5

# ~35s wall time observed for the slowest (2K) run on this box; wide margin
# for a loaded CI host without letting a genuinely stuck process hang the gate.
_TIMEOUT_S = 180

# Rough per-row on-disk footprint once Parquet-encoded (short numeric-string
# key + two int columns): comfortably pessimistic vs. the ~30-45 bytes/row
# actually observed, so the floor check below trips before a real ENOSPC.
_BYTES_PER_ROW_ESTIMATE = 80
_DISK_FLOOR_BYTES = int(
    2 * _KEYS * _DUPLICATE_RATIO * _BYTES_PER_ROW_ESTIMATE * 4
)  # x4 for scratch

_WORKER_SCRIPT = textwrap.dedent(
    '''
    """Fresh-subprocess worker: builds a synthetic (key, row_nr, payload)
    staged parquet with a chosen distinct-key count, runs either the SPLIT
    dedup (winners COPY'd to disk, then a separate join-back) or the
    pre-split COMBINED dedup (winners aggregate as an inline join subquery)
    against it, and reports peak RSS plus the query outcome as one JSON line
    on stdout. Not a committed module -- written to a temp file by the perf
    test that drives it, mirroring test_ooc_external_sort_memory.py's own
    pattern, so it only runs inside a pinned, disposable subprocess."""

    import argparse
    import json
    import time
    from pathlib import Path

    ROW_NR = "__decoy_row_nr"
    KEY = "__decoy_fk_join_key"
    VAL = "__decoy_masked_key"


    def _peak_rss_mb() -> float:
        # VmHWM, not ru_maxrss: see this test module's docstring.
        for line in Path("/proc/self/status").read_text().splitlines():
            if line.startswith("VmHWM:"):
                return int(line.split()[1]) / 1024.0
        raise RuntimeError("VmHWM not found in /proc/self/status")


    def main() -> None:
        parser = argparse.ArgumentParser()
        parser.add_argument("--mode", choices=["split", "combined"], required=True)
        parser.add_argument("--keys", type=int, required=True)
        parser.add_argument("--rows", type=int, required=True)
        parser.add_argument("--limit-mib", type=int, required=True)
        parser.add_argument("--work-dir", type=str, required=True)
        args = parser.parse_args()

        import duckdb

        work_dir = Path(args.work_dir)
        work_dir.mkdir(parents=True, exist_ok=True)
        duckdb_tmp = work_dir / "duckdb_tmp"
        duckdb_tmp.mkdir(parents=True, exist_ok=True)
        # Config mirrors `out_of_core/_duckdb.py::connect_duckdb`: a bare
        # `duckdb.connect` here (not importing decoy_engine) keeps this
        # worker's own import-time RSS out of the measurement, and the
        # thread count matches what `connect_duckdb` itself derives for this
        # memory_limit (`_threads_for_memory_limit`: 350 MiB // 2 GiB rounds
        # to 0, floored to 1), so this reproduces the SAME DuckDB execution
        # shape production actually runs under, not a more/less parallel one.
        conn = duckdb.connect(
            database=":memory:",
            config={
                "temp_directory": str(duckdb_tmp),
                "preserve_insertion_order": False,
                "memory_limit": f"{args.limit_mib}MB",
                "threads": 1,
            },
        )

        staged_path = str(work_dir / "staged.parquet")
        ok = True
        error_class = None
        error_message = None
        peak_before_query_mb = None
        try:
            # One vectorized DuckDB-native COPY generates the fixture: no
            # Python-side per-row construction, so the fixture generation
            # itself stays outside what this test measures. `i % keys`
            # yields exactly `keys` distinct join keys; rows beyond `keys`
            # (from `--rows > --keys`) revisit an already-seen key with a
            # LATER row_nr, giving the dedup genuine last-write-wins work.
            conn.execute(
                f"""
                COPY (
                    SELECT (i % {args.keys})::VARCHAR AS {KEY},
                           i AS {ROW_NR},
                           (i % 997) AS {VAL}
                    FROM generate_series(0, {args.rows} - 1) AS t(i)
                ) TO '{staged_path}' (FORMAT PARQUET)
                """
            )
            peak_before_query_mb = _peak_rss_mb()
            staged_sql = f"read_parquet('{staged_path}')"
            out_path = str(work_dir / "out.parquet")
            t0 = time.monotonic()
            if args.mode == "split":
                winners_path = str(work_dir / "winners.parquet")
                conn.execute(
                    f"""
                    COPY (
                        SELECT {KEY}, max({ROW_NR}) AS __decoy_win_row_nr
                        FROM {staged_sql}
                        GROUP BY {KEY}
                    ) TO '{winners_path}' (FORMAT PARQUET)
                    """
                )
                winners_sql = f"read_parquet('{winners_path}')"
                conn.execute(
                    f"""
                    COPY (
                        SELECT s.{KEY}, s.{VAL}
                        FROM {staged_sql} s
                        JOIN {winners_sql} w
                          ON s.{KEY} = w.{KEY}
                         AND s.{ROW_NR} = w.__decoy_win_row_nr
                    ) TO '{out_path}' (FORMAT PARQUET)
                    """
                )
            else:
                # The exact pre-split shape `_relation.py::_build_relation`
                # replaced: the winners aggregate as an inline subquery of
                # the join-back, one COPY statement, one physical plan.
                conn.execute(
                    f"""
                    COPY (
                        SELECT s.{KEY}, s.{VAL}
                        FROM {staged_sql} s
                        JOIN (
                            SELECT {KEY}, max({ROW_NR}) AS __decoy_win_row_nr
                            FROM {staged_sql}
                            GROUP BY {KEY}
                        ) w
                          ON s.{KEY} = w.{KEY}
                         AND s.{ROW_NR} = w.__decoy_win_row_nr
                    ) TO '{out_path}' (FORMAT PARQUET)
                    """
                )
            wall_time_s = time.monotonic() - t0
        except Exception as exc:  # noqa: BLE001 -- reported to the parent, never swallowed
            ok = False
            error_class = type(exc).__name__
            error_message = str(exc)[:500]
            wall_time_s = None
        finally:
            conn.close()

        print(
            json.dumps(
                {
                    "mode": args.mode,
                    "keys": args.keys,
                    "rows": args.rows,
                    "limit_mib": args.limit_mib,
                    "ok": ok,
                    "error_class": error_class,
                    "error_message": error_message,
                    "peak_before_query_mb": peak_before_query_mb,
                    "peak_rss_mb": _peak_rss_mb(),
                    "wall_time_s": wall_time_s,
                }
            )
        )


    if __name__ == "__main__":
        main()
    '''
)

# DuckDB exception classes that specifically mean "ran out of memory or a
# similar resource", matched on TYPE (never a bare `except Exception`): any
# other failure (a SQL typo, a fixture I/O error, a subprocess crash) must
# fail this test rather than be mistaken for the expected control.
_RECOGNIZED_RESOURCE_ERROR_CLASSES = frozenset({"OutOfMemoryException"})


def _run_worker(tmp_path, *, mode: str, keys: int, rows: int, limit_mib: int) -> dict:
    worker_path = tmp_path / f"_dedup_memory_worker_{mode}_{keys}.py"
    worker_path.write_text(_WORKER_SCRIPT)
    work_dir = tmp_path / f"work_{mode}_{keys}"
    env = {**os.environ, **_CAPPED_ENV}
    cmd = [
        sys.executable,
        str(worker_path),
        "--mode",
        mode,
        "--keys",
        str(keys),
        "--rows",
        str(rows),
        "--limit-mib",
        str(limit_mib),
        "--work-dir",
        str(work_dir),
    ]
    proc = subprocess.run(  # noqa: S603
        cmd, capture_output=True, text=True, timeout=_TIMEOUT_S, env=env
    )
    assert proc.returncode == 0, (
        f"worker subprocess failed (code {proc.returncode}):\n{proc.stderr}"
    )
    return json.loads(proc.stdout.strip().splitlines()[-1])


def _check_disk_floor(tmp_path) -> None:
    free_bytes = shutil.disk_usage(tmp_path).free
    if free_bytes < _DISK_FLOOR_BYTES:
        pytest.skip(
            f"only {free_bytes / (1 << 20):.0f} MiB free, need at least "
            f"~{_DISK_FLOOR_BYTES / (1 << 20):.0f} MiB to size the K/2K fixture "
            "safely -- INCONCLUSIVE, not a pass on an undersized run"
        )


def test_out_of_core_relation_dedup_memory_plateau(tmp_path):
    """The split form's OWN boundedness: flat peak RSS from K to 2K distinct
    keys, both within a fixed envelope of the DuckDB memory_limit. Kept as a
    SEPARATE test from the negative control below (not merely a separate
    assertion in one test body) so a real regression here can never be
    masked by that control's `xfail`: pytest's xfail applies to whichever
    single test function it decorates, and this one carries none.
    """
    _check_disk_floor(tmp_path)
    rows_k = int(_KEYS * _DUPLICATE_RATIO)
    rows_2k = int(2 * _KEYS * _DUPLICATE_RATIO)

    split_k = _run_worker(tmp_path, mode="split", keys=_KEYS, rows=rows_k, limit_mib=_LIMIT_MIB)
    split_2k = _run_worker(
        tmp_path, mode="split", keys=2 * _KEYS, rows=rows_2k, limit_mib=_LIMIT_MIB
    )

    assert split_k["ok"] is True, split_k
    assert split_2k["ok"] is True, split_2k
    envelope_mb = _LIMIT_MIB * _ENVELOPE_FACTOR
    assert split_k["peak_rss_mb"] <= envelope_mb, (
        f"split@K peak RSS {split_k['peak_rss_mb']:.1f} MB exceeds the "
        f"{envelope_mb:.1f} MB envelope ({_ENVELOPE_FACTOR}x {_LIMIT_MIB} MiB)"
    )
    assert split_2k["peak_rss_mb"] <= envelope_mb, (
        f"split@2K peak RSS {split_2k['peak_rss_mb']:.1f} MB exceeds the "
        f"{envelope_mb:.1f} MB envelope ({_ENVELOPE_FACTOR}x {_LIMIT_MIB} MiB)"
    )
    assert split_2k["peak_rss_mb"] <= _PLATEAU_FACTOR * split_k["peak_rss_mb"], (
        f"split@2K peak RSS {split_2k['peak_rss_mb']:.1f} MB grew more than "
        f"{_PLATEAU_FACTOR}x split@K's {split_k['peak_rss_mb']:.1f} MB -- "
        "O(distinct-key) growth, not a plateau"
    )


@pytest.mark.xfail(
    reason=(
        "negative control unresolved (see module docstring FINDING, 2026-09-02): "
        "the pre-split combined form does not measurably lose to the split form "
        "on this box/DuckDB 1.5.4 at any probed K/L; escalated to Cam/Codex "
        "rather than weakened. The plateau proof this control complements lives "
        "in a separate, non-xfail test above so a real regression there cannot "
        "hide behind this marker."
    ),
    strict=True,
)
def test_out_of_core_relation_dedup_combined_negative_control(tmp_path):
    """The pre-split combined form must lose to the split form at K, or raise
    a recognized memory/resource error -- the plan's own negative control, so
    a broken split-vs-combined comparison (e.g. an accidentally-inert split)
    cannot slip through the plateau test above by coincidence.
    """
    _check_disk_floor(tmp_path)
    rows_k = int(_KEYS * _DUPLICATE_RATIO)

    split_k = _run_worker(tmp_path, mode="split", keys=_KEYS, rows=rows_k, limit_mib=_LIMIT_MIB)
    combined_k = _run_worker(
        tmp_path, mode="combined", keys=_KEYS, rows=rows_k, limit_mib=_LIMIT_MIB
    )
    assert split_k["ok"] is True, split_k

    materially_worse = combined_k["ok"] and (
        combined_k["peak_rss_mb"] >= _NEGATIVE_CONTROL_FACTOR * split_k["peak_rss_mb"]
    )
    recognized_oom = (not combined_k["ok"]) and (
        combined_k["error_class"] in _RECOGNIZED_RESOURCE_ERROR_CLASSES
    )
    if not combined_k["ok"] and not recognized_oom:
        pytest.fail(
            "combined@K failed with an UNRECOGNIZED error, not the expected "
            f"memory/resource control: {combined_k['error_class']}: "
            f"{combined_k['error_message']}"
        )
    assert materially_worse or recognized_oom, (
        f"expected the pre-split combined form to peak >= "
        f"{_NEGATIVE_CONTROL_FACTOR}x the split form's "
        f"{split_k['peak_rss_mb']:.1f} MB, or raise a recognized OOM; got "
        f"peak_rss_mb={combined_k['peak_rss_mb']:.1f}, ok={combined_k['ok']}, "
        f"error_class={combined_k['error_class']}"
    )
