#!/usr/bin/env python3
"""Generate the engine capability matrix from the live registries.

Source of truth is the code, not the prose. This script imports decoy_engine
and walks its registries (mask strategies, generation strategies, synthetic
providers, connectors + capabilities, STORM detectors, disguises) and emits a
markdown table set that is correct by construction.

Run:  python scripts/gen_capability_matrix.py
Out:  docs/capability-matrix.md  (committed; the guard test re-runs this and
      diffs, so a new capability with no doc entry fails CI)

When a registry import path moves, fix it here once. Keep this script the only
place that knows how to read the registries for docs.
"""

from __future__ import annotations

import io
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "docs" / "capability-matrix.md"

HEADER = """# Engine capability matrix

<!-- GENERATED by scripts/gen_capability_matrix.py - DO NOT EDIT BY HAND. -->
<!-- Run `python scripts/gen_capability_matrix.py` to regenerate. -->

This is the authoritative list of what the engine can do, read straight from
the registries in `src/decoy_engine/`. Narrative guides (strategies, connector
support, disguises) must agree with this file; the drift-guard test enforces it.
"""


def _mask_strategies() -> list[tuple[str, str, str]]:
    from decoy_engine.execution._strategies import SCALAR_HANDLERS
    from decoy_engine.execution._technique_class import TECHNIQUE_CLASS_BY_STRATEGY

    try:
        from decoy_engine.execution.polars._strategies import POLARS_SCALAR_HANDLERS

        polars = set(POLARS_SCALAR_HANDLERS)
    except Exception:
        polars = set()
    rows = []
    for name in sorted(SCALAR_HANDLERS):
        if name == "nested":
            # A wrapper, not a leaf strategy: it requires a child strategy and is
            # excluded from the counted strategy surface (the proof manifest and
            # its guard use the same convention). Documented in the note below so
            # it is not forgotten when surfacing capabilities.
            continue
        gdpr = str(TECHNIQUE_CLASS_BY_STRATEGY.get(name, "-"))
        accel = "yes" if name in polars else "no"
        rows.append((name, gdpr, accel))
    return rows


def _generation_strategies() -> list[str]:
    # Authoritative source is the V2 config Literal on
    # GenerateColumnConfig.type (the validation choke point every
    # generate column passes through); union with V1's ColumnGenerator
    # dispatch keys for any legacy-only type.
    import typing

    names: set[str] = set()
    try:
        from decoy_engine.config._tables import GenerateColumnConfig

        names.update(typing.get_args(GenerateColumnConfig.model_fields["type"].annotation))
    except Exception:
        pass
    try:
        from decoy_engine.generators.columns import ColumnGenerator

        names.update(ColumnGenerator(seed=0).generators.keys())
    except Exception:
        pass
    return sorted(names)


def _providers() -> list[tuple[str, str, str, str]]:
    # Audit M3 (2026-06-12): walk the LIVE registry, not _CATALOG.
    # _CATALOG carries only the Faker-bound subset (19), silently
    # omitting the DecoyNative identifier providers and the composites;
    # the registry is the runtime truth (34 at the time of this fix).
    import importlib.util

    import decoy_engine
    from decoy_engine.providers_v2 import get_default_registry

    # Adopted Mimesis providers bind to faker or mimesis depending on whether
    # the optional extra is installed. The doc must not depend on the
    # generating machine's install state, so render the combined label.
    # _adoption_matrix is pure data, but a normal import executes the
    # mimesis package __init__, which raises when the extra is absent
    # (CI installs [dev] only) -- so load the data module straight from
    # its file, bypassing the package init.
    matrix_path = (
        Path(decoy_engine.__file__).parent / "providers_v2" / "mimesis" / "_adoption_matrix.py"
    )
    spec = importlib.util.spec_from_file_location("_decoy_adoption_matrix", matrix_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load adoption matrix from {matrix_path}")
    matrix_mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(matrix_mod)
    adopted_mimesis = frozenset(matrix_mod.ADOPTED_MIMESIS_PROVIDERS)

    registry = get_default_registry()
    rows = []
    for name in sorted(registry.known_providers()):
        d = registry.get_capabilities(name).model_dump()
        backend = d.get("backend_type") or ""
        if name in adopted_mimesis:
            backend = "faker (mimesis with the `mimesis` extra)"
        deterministic = "yes" if d.get("supports_deterministic") else "no"
        unique = "yes" if d.get("supports_uniqueness") else "no"
        rows.append((str(name), str(backend), deterministic, unique))
    return sorted(rows)


def _connectors() -> tuple[list[str], list[tuple[str, dict]]]:
    import decoy_engine.connectors as conn
    from decoy_engine import sdk

    cap_consts = [v for n, v in vars(sdk).items() if n.startswith("CAP_")]
    cap_order = sorted(cap_consts)
    rows = []
    for cls_name in (
        "S3FileSource",
        "S3FileSink",
        "GCSFileSource",
        "GCSFileSink",
        "SFTPFileSource",
        "SFTPFileSink",
    ):
        cls = getattr(conn, cls_name, None)
        if cls is None:
            continue
        caps = dict(getattr(cls, "capabilities", {}) or {})
        rows.append((cls_name, caps))
    return cap_order, rows


def _detectors() -> list[tuple[str, str]]:
    from decoy_engine.storm.detectors import _SPAN_DETECTORS, REGISTERED_DETECTORS

    span = {getattr(f, "__name__", "") for f in _SPAN_DETECTORS}
    rows = []
    for fn in REGISTERED_DETECTORS:
        fname = getattr(fn, "__name__", str(fn))
        label = fname[len("detect_") :] if fname.startswith("detect_") else fname
        kind = "span" if fname in span else "value"
        rows.append((label, kind))
    return sorted(rows)


def _disguises() -> list[tuple[str, str, int]]:
    from decoy_engine.disguises import load_disguises

    rows = []
    for d in load_disguises():
        rules = getattr(d, "field_rules", []) or []
        rows.append((str(getattr(d, "id", "?")), str(getattr(d, "name", "?")), len(rules)))
    return sorted(rows)


def _checksum_schemes() -> list[str]:
    # FPE `checksum:` re-derives one of these after masking so the output
    # stays a valid identifier. Read from the validator registry.
    from decoy_engine.checksums import _KNOWN_SCHEMES

    return sorted(_KNOWN_SCHEMES)


def _execution_architecture() -> dict[str, object]:
    # The routing/substrate surface a caller can select or that the planner
    # picks. Read from the live constants so this stays correct as routes are
    # added. The native-route and OOC-reorder rows are what a Platform
    # "route taken" indicator or a job-time estimator would surface.
    from decoy_engine.execution._planner import EXECUTION_MODES
    from decoy_engine.execution._substrate import _DEFAULT_SUBSTRATE, VALID_SUBSTRATES
    from decoy_engine.execution.native._requirements import (
        NATIVE_KERNEL_STRATEGIES,
        NATIVE_POOL_STRATEGIES,
    )
    from decoy_engine.execution.out_of_core._route_policy import REORDER_PARENT_KEY_THRESHOLD

    return {
        "substrates": list(VALID_SUBSTRATES),
        "default_substrate": _DEFAULT_SUBSTRATE,
        "modes": list(EXECUTION_MODES),
        "native_kernel": sorted(NATIVE_KERNEL_STRATEGIES),
        "native_pool": sorted(NATIVE_POOL_STRATEGIES),
        "reorder_threshold": int(REORDER_PARENT_KEY_THRESHOLD),
    }


def render() -> str:
    out = io.StringIO()
    w = out.write
    w(HEADER)

    mask = _mask_strategies()
    w(f"\n## Mask strategies ({len(mask)})\n\n")
    w("| Strategy | GDPR technique class | Polars-accelerated |\n")
    w("| --- | --- | --- |\n")
    for name, gdpr, accel in mask:
        w(f"| `{name}` | {gdpr} | {accel} |\n")
    w(
        "\n`nested` is a wrapper strategy: it walks JSON in each cell and applies "
        "a child strategy to the leaf values a JSONPath matches, then reassembles "
        "the JSON. Configure it with a nested child strategy.\n"
    )

    gen = _generation_strategies()
    w(f"\n## Generation strategies ({len(gen)})\n\n")
    w(", ".join(f"`{g}`" for g in gen) + "\n")

    prov = _providers()
    w(f"\n## Synthetic providers ({len(prov)})\n\n")
    w("| Provider | Backend | Deterministic | Unique |\n| --- | --- | --- | --- |\n")
    for name, backend, det, uniq in prov:
        w(f"| `{name}` | {backend} | {det} | {uniq} |\n")

    cap_order, conns = _connectors()
    w(f"\n## Connectors ({len(conns)})\n\n")
    short = [c.replace("supports_", "") for c in cap_order]
    w("| Connector | " + " | ".join(short) + " |\n")
    w("| --- | " + " | ".join("---" for _ in short) + " |\n")
    for cls_name, caps in conns:
        cells = ["yes" if caps.get(c) else "-" for c in cap_order]
        w(f"| `{cls_name}` | " + " | ".join(cells) + " |\n")

    det = _detectors()
    w(f"\n## STORM detectors ({len(det)})\n\n")
    w("| Detector | Match kind |\n| --- | --- |\n")
    for label, kind in det:
        w(f"| `{label}` | {kind} |\n")

    dis = _disguises()
    w(f"\n## Disguises ({len(dis)})\n\n")
    w("| ID | Name | Field rules |\n| --- | --- | --- |\n")
    for did, name, n in dis:
        w(f"| `{did}` | {name} | {n} |\n")

    schemes = _checksum_schemes()
    w(f"\n## Checksum / FPE schemes ({len(schemes)})\n\n")
    w(
        "The `fpe` strategy's `checksum:` parameter re-derives a valid check "
        "digit after masking so the output stays a well-formed identifier.\n\n"
    )
    w(", ".join(f"`{s}`" for s in schemes) + "\n")

    arch = _execution_architecture()
    w("\n## Execution architecture\n\n")
    w(
        "How a job runs: which substrate computes it and which route the planner "
        "takes. Everything here is a real, user-visible knob or an automatic route "
        "the engine selects.\n\n"
    )
    w("| Surface | Values | Notes |\n| --- | --- | --- |\n")
    subs = ", ".join(f"`{s}`" for s in arch["substrates"])  # type: ignore[union-attr]
    w(
        f"| Substrate (`substrate=` / `DECOY_SUBSTRATE`) | {subs} | "
        f"default `{arch['default_substrate']}` |\n"
    )
    modes = ", ".join(f"`{m}`" for m in arch["modes"])  # type: ignore[union-attr]
    w(
        f"| Execution modes (planner ladder, `explain_plan=True`) | {modes} | "
        "fastest-first; the planner picks and reports the route |\n"
    )
    nk = ", ".join(f"`{s}`" for s in arch["native_kernel"])  # type: ignore[union-attr]
    npool = ", ".join(f"`{s}`" for s in arch["native_pool"])  # type: ignore[union-attr]
    w(
        f"| Native columnar route (`native_route_enabled=True`, default off) | "
        f"kernels: {nk}; pool: {npool} | single-table non-FK lane; never "
        "materializes the source; byte-parity to the oracle |\n"
    )
    w(
        f"| Out-of-core FK route | batch-join (default) vs reorder | reorder auto-"
        f"selected per table when the deduped parent-key count >= "
        f"{arch['reorder_threshold']:,} (override `out_of_core_reorder_threshold_rows`) |\n"
    )

    w("\n## Extensibility and formats\n\n")
    w(
        "- **Custom providers**: drop-in Python modules register new synthetic "
        "providers at process start via `providers_v2` `register()`; the planner "
        "closed-checks them (see `custom_providers/README.md`).\n"
    )
    w(
        "- **Fixed-width sources**: fixed-width flat files are a first-class source "
        "format (`config._fixed_width` layout + `profile._fixed_width_reader`), "
        "alongside Parquet / CSV and the S3 / GCS / SFTP connectors above.\n"
    )
    w(
        "- **Rust companion (`decoy-engine-native`)**: an optional compiled `native` "
        "extra shipping a keyed-derivation kernel (HKDF-SHA256 + HMAC-SHA256 over "
        "Arrow) that reproduces the `hash` strategy byte-for-byte. Built and "
        "fuzz-tested; the production loader is not yet wired (a separate slice).\n"
    )

    return out.getvalue()


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
