#!/usr/bin/env python3
"""Generate the engine capability matrix from the live registries.

Source of truth is the code, not the prose. This script imports decoy_engine
and walks its registries (mask strategies, generation strategies, synthetic
providers, connectors + capabilities, STORM detectors, disguises) and emits a
markdown table set that is correct by construction.

Run:  python scripts/gen_capability_matrix.py
Out:  docs/capability-matrix.md  (committed; the guard test re-runs this and
      diffs, so a new capability with no doc entry fails CI)

When a registry import path moves, fix it here once. Keep this script the only
place that knows how to read the registries for docs.
"""

from __future__ import annotations

import io
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "docs" / "capability-matrix.md"

HEADER = """# Engine capability matrix

<!-- GENERATED by scripts/gen_capability_matrix.py - DO NOT EDIT BY HAND. -->
<!-- Run `python scripts/gen_capability_matrix.py` to regenerate. -->

This is the authoritative list of what the engine can do, read straight from
the registries in `src/decoy_engine/`. Narrative guides (strategies, connector
support, disguises) must agree with this file; the drift-guard test enforces it.
"""


def _mask_strategies() -> list[tuple[str, str, str]]:
    from decoy_engine.execution._strategies import SCALAR_HANDLERS
    from decoy_engine.execution._technique_class import TECHNIQUE_CLASS_BY_STRATEGY

    try:
        from decoy_engine.execution.polars._strategies import POLARS_SCALAR_HANDLERS

        polars = set(POLARS_SCALAR_HANDLERS)
    except Exception:
        polars = set()
    rows = []
    for name in sorted(SCALAR_HANDLERS):
        if name == "nested":
            continue  # wrapper, not a user-facing strategy
        gdpr = str(TECHNIQUE_CLASS_BY_STRATEGY.get(name, "-"))
        accel = "yes" if name in polars else "no"
        rows.append((name, gdpr, accel))
    return rows


def _generation_strategies() -> list[str]:
    # Authoritative dispatch dict is ColumnGenerator.generators (instance-built).
    # Construct with a fixed seed and read the keys; fall back to source parse.
    try:
        from decoy_engine.generators.columns import ColumnGenerator

        return sorted(ColumnGenerator(seed=0).generators.keys())
    except Exception:
        import inspect
        import re

        from decoy_engine.generators import columns

        src = inspect.getsource(columns)
        return sorted(set(re.findall(r'"([a-z_]+)"\s*:\s*self\._generate_', src)))


def _providers() -> list[tuple[str, str, str, str]]:
    # Audit M3 (2026-06-12): walk the LIVE registry, not _CATALOG.
    # _CATALOG carries only the Faker-bound subset (19), silently
    # omitting the DecoyNative identifier providers and the composites;
    # the registry is the runtime truth (34 at the time of this fix).
    from decoy_engine.providers_v2 import get_default_registry

    registry = get_default_registry()
    rows = []
    for name in sorted(registry.known_providers()):
        d = registry.get_capabilities(name).model_dump()
        backend = d.get("backend_type") or ""
        deterministic = "yes" if d.get("supports_deterministic") else "no"
        unique = "yes" if d.get("supports_uniqueness") else "no"
        rows.append((str(name), str(backend), deterministic, unique))
    return sorted(rows)


def _connectors() -> tuple[list[str], list[tuple[str, dict]]]:
    import decoy_engine.connectors as conn
    from decoy_engine import sdk

    cap_consts = [v for n, v in vars(sdk).items() if n.startswith("CAP_")]
    cap_order = sorted(cap_consts)
    rows = []
    for cls_name in (
        "S3FileSource",
        "S3FileSink",
        "GCSFileSource",
        "GCSFileSink",
        "SFTPFileSource",
        "SFTPFileSink",
    ):
        cls = getattr(conn, cls_name, None)
        if cls is None:
            continue
        caps = dict(getattr(cls, "capabilities", {}) or {})
        rows.append((cls_name, caps))
    return cap_order, rows


def _detectors() -> list[tuple[str, str]]:
    from decoy_engine.storm.detectors import _SPAN_DETECTORS, REGISTERED_DETECTORS

    span = {getattr(f, "__name__", "") for f in _SPAN_DETECTORS}
    rows = []
    for fn in REGISTERED_DETECTORS:
        fname = getattr(fn, "__name__", str(fn))
        label = fname[len("detect_") :] if fname.startswith("detect_") else fname
        kind = "span" if fname in span else "value"
        rows.append((label, kind))
    return sorted(rows)


def _disguises() -> list[tuple[str, str, int]]:
    from decoy_engine.disguises import load_disguises

    rows = []
    for d in load_disguises():
        rules = getattr(d, "field_rules", []) or []
        rows.append((str(getattr(d, "id", "?")), str(getattr(d, "name", "?")), len(rules)))
    return sorted(rows)


def render() -> str:
    out = io.StringIO()
    w = out.write
    w(HEADER)

    mask = _mask_strategies()
    w(f"\n## Mask strategies ({len(mask)})\n\n")
    w("| Strategy | GDPR technique class | Polars-accelerated |\n")
    w("| --- | --- | --- |\n")
    for name, gdpr, accel in mask:
        w(f"| `{name}` | {gdpr} | {accel} |\n")
    w("\n`nested` is an internal wrapper, not a user-facing strategy.\n")

    gen = _generation_strategies()
    w(f"\n## Generation strategies ({len(gen)})\n\n")
    w(", ".join(f"`{g}`" for g in gen) + "\n")

    prov = _providers()
    w(f"\n## Synthetic providers ({len(prov)})\n\n")
    w("| Provider | Backend | Deterministic | Unique |\n| --- | --- | --- | --- |\n")
    for name, backend, det, uniq in prov:
        w(f"| `{name}` | {backend} | {det} | {uniq} |\n")

    cap_order, conns = _connectors()
    w(f"\n## Connectors ({len(conns)})\n\n")
    short = [c.replace("supports_", "") for c in cap_order]
    w("| Connector | " + " | ".join(short) + " |\n")
    w("| --- | " + " | ".join("---" for _ in short) + " |\n")
    for cls_name, caps in conns:
        cells = ["yes" if caps.get(c) else "-" for c in cap_order]
        w(f"| `{cls_name}` | " + " | ".join(cells) + " |\n")

    det = _detectors()
    w(f"\n## STORM detectors ({len(det)})\n\n")
    w("| Detector | Match kind |\n| --- | --- |\n")
    for label, kind in det:
        w(f"| `{label}` | {kind} |\n")

    dis = _disguises()
    w(f"\n## Disguises ({len(dis)})\n\n")
    w("| ID | Name | Field rules |\n| --- | --- | --- |\n")
    for did, name, n in dis:
        w(f"| `{did}` | {name} | {n} |\n")

    return out.getvalue()


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
