"""ROADMAP Item 6 — `pipeline_derive_key` from ExecutionContext flows
into ColumnGenerator's per-column seeding.

Without this thread, generation falls back to `seed + hash(name)` per
column. That's reproducible *given the same YAML*, but it's not tied to
the tenant master key — so the "lose the DB, restore the master key,
output reproduces" story only holds for mask. These tests guard the
property on the generation side: same master + same pipeline_label →
same generated bytes across two completely fresh DataGenerator
instances.
"""

from __future__ import annotations

import pandas as pd
import yaml

from decoy_engine import DataGenerator, ExecutionContext, make_key_resolver

MASTER_A = b"\x00" * 32
MASTER_B = b"\xff" * 32


def _write_minimal_config(tmp_path) -> str:
    """A tiny config that exercises both faker and formula columns —
    enough to prove the keyed path is firing without the noise of the
    full sample fixture."""
    config = {
        "generator_settings": {
            "seed": 42,
            "output_directory": str(tmp_path),
            "chunk_size": 1000,
        },
        "tables": [
            {
                "name": "customers",
                "rows": 5,
                "output_path": str(tmp_path / "customers.csv"),
                "columns": [
                    {
                        "name": "customer_id",
                        "type": "sequence",
                        "start": 1,
                        "prefix": "C",
                        "pad_length": 4,
                    },
                    {"name": "first_name", "type": "faker", "faker_type": "first_name"},
                    {"name": "last_name", "type": "faker", "faker_type": "last_name"},
                ],
            },
        ],
    }
    path = tmp_path / "gen_config.yaml"
    with open(path, "w") as fh:
        yaml.dump(config, fh)
    return str(path)


def _run_generator(tmp_path, ctx) -> pd.DataFrame:
    tmp_path.mkdir(parents=True, exist_ok=True)
    config_path = _write_minimal_config(tmp_path)
    DataGenerator(config_path, ctx=ctx).generate()
    return pd.read_csv(tmp_path / "customers.csv")


class TestPipelineDeriveKeyThreadedThrough:
    def test_same_master_same_label_two_instances_identical_output(self, tmp_path):
        """The full Item 6 contract: two DataGenerator instances built
        from identical inputs produce byte-identical output. Proves the
        `pipeline_derive_key` resolver makes it from ctx → ColumnGenerator
        → per-column seed."""
        ctx_a = ExecutionContext(
            pipeline_derive_key=make_key_resolver(MASTER_A, "customers_q4"),
        )
        df_a = _run_generator(tmp_path / "a", ctx_a)

        ctx_b = ExecutionContext(
            pipeline_derive_key=make_key_resolver(MASTER_A, "customers_q4"),
        )
        df_b = _run_generator(tmp_path / "b", ctx_b)

        pd.testing.assert_frame_equal(df_a, df_b)

    def test_different_pipeline_label_yields_different_output(self, tmp_path):
        """Same master but different pipeline_label should produce
        different bytes — that's the point of the per-pipeline scope."""
        ctx_a = ExecutionContext(
            pipeline_derive_key=make_key_resolver(MASTER_A, "customers_q4"),
        )
        ctx_b = ExecutionContext(
            pipeline_derive_key=make_key_resolver(MASTER_A, "customers_q1"),
        )
        df_a = _run_generator(tmp_path / "a", ctx_a)
        df_b = _run_generator(tmp_path / "b", ctx_b)

        # First name should differ between two pipelines under the same
        # master — different pipeline_label means a different per-column
        # subkey, which means a different per-row Faker seed.
        assert not df_a["first_name"].equals(df_b["first_name"]), (
            "pipeline_label change had no effect on generated faker output — "
            "the resolver wasn't threaded through"
        )

    def test_different_master_yields_different_output(self, tmp_path):
        """Cross-tenant property: two different tenants with the same
        pipeline_label produce different generated bytes."""
        ctx_a = ExecutionContext(
            pipeline_derive_key=make_key_resolver(MASTER_A, "customers_q4"),
        )
        ctx_b = ExecutionContext(
            pipeline_derive_key=make_key_resolver(MASTER_B, "customers_q4"),
        )
        df_a = _run_generator(tmp_path / "a", ctx_a)
        df_b = _run_generator(tmp_path / "b", ctx_b)

        assert not df_a["first_name"].equals(df_b["first_name"])

    def test_no_resolver_falls_back_to_legacy_seed_path(self, tmp_path):
        """Backwards compat: when ExecutionContext has no
        pipeline_derive_key (ctx is None or the field is None),
        DataGenerator must still run end-to-end. Pre-Item-6 callers and
        unit tests work unchanged."""
        df = _run_generator(tmp_path / "fallback", ctx=None)
        assert len(df) == 5
        # Sequence column doesn't depend on the resolver — sanity check
        # that some output landed at all.
        assert list(df["customer_id"]) == ["C0001", "C0002", "C0003", "C0004", "C0005"]


# ── ROADMAP Item 7 — `determinism: fresh` per-column opt-out ─────────────────


def _write_fresh_mode_config(tmp_path) -> str:
    """Config exercising every strategy that uses `_column_seed`:
    faker (first_name), categorical (status), and formula (price). Each
    column uses `determinism: fresh` so the test can prove the override
    fires regardless of strategy."""
    config = {
        "generator_settings": {
            "seed": 42,
            "output_directory": str(tmp_path),
            "chunk_size": 1000,
        },
        "tables": [
            {
                "name": "orders",
                "rows": 10,
                "output_path": str(tmp_path / "orders.csv"),
                "columns": [
                    # Stable across runs — no `determinism: fresh`.
                    {
                        "name": "order_id",
                        "type": "sequence",
                        "start": 1,
                        "prefix": "O",
                        "pad_length": 4,
                    },
                    {"name": "customer", "type": "faker", "faker_type": "first_name"},
                    # Fresh mode — every run rolls.
                    {
                        "name": "price",
                        "type": "formula",
                        "formula": "round(randint(1000, 50000) / 100, 2)",
                        "determinism": "fresh",
                    },
                    {
                        "name": "status",
                        "type": "categorical",
                        "categories": ["new", "shipped", "delivered"],
                        "determinism": "fresh",
                    },
                ],
            },
        ],
    }
    path = tmp_path / "gen_config.yaml"
    with open(path, "w") as fh:
        yaml.dump(config, fh)
    return str(path)


def _run_fresh_generator(tmp_path) -> pd.DataFrame:
    tmp_path.mkdir(parents=True, exist_ok=True)
    config_path = _write_fresh_mode_config(tmp_path)
    ctx = ExecutionContext(
        pipeline_derive_key=make_key_resolver(MASTER_A, "orders_q4"),
    )
    DataGenerator(config_path, ctx=ctx).generate()
    return pd.read_csv(tmp_path / "orders.csv")


class TestFreshDeterminism:
    def test_fresh_columns_roll_across_runs_under_same_key(self, tmp_path):
        """Two runs under the same master + pipeline_label produce
        DIFFERENT values for fresh-mode columns. Default (non-fresh)
        columns stay identical."""
        df_a = _run_fresh_generator(tmp_path / "a")
        df_b = _run_fresh_generator(tmp_path / "b")

        # Stable: same key + same column without `fresh` → identical.
        assert df_a["order_id"].equals(df_b["order_id"])
        assert df_a["customer"].equals(df_b["customer"]), (
            "non-fresh faker column should be byte-identical across runs"
        )

        # Fresh: should differ between runs. We use approximate equality
        # because price uses `randint(1000, 50000)` so the chance of a
        # collision on the *full series* is vanishingly small but non-zero
        # for any single row — assert the series differs as a whole.
        assert not df_a["price"].equals(df_b["price"]), "fresh formula column should roll per run"
        # Categorical with 3 categories has higher collision odds per
        # row, but across 10 rows two random sequences are extremely
        # unlikely to match exactly.
        assert not df_a["status"].equals(df_b["status"]), (
            "fresh categorical column should roll per run"
        )

    def test_fresh_column_is_internally_consistent_within_a_run(self, tmp_path):
        """Within a single run, a fresh-mode column still produces a
        value per row using `column_seed + row_index`. Re-generating
        the same config in one process should give the same series for
        non-fresh columns and the row-by-row consistency for fresh
        columns is implicit (each row index always reads the same seed
        offset off the run's column_seed)."""
        df = _run_fresh_generator(tmp_path / "consistency")
        # Sanity: 10 rows landed for every column.
        assert len(df) == 10
        # Fresh columns produced valid values, not Nones / errors.
        assert df["price"].notna().all()
        assert df["status"].notna().all()
        assert set(df["status"].unique()) <= {"new", "shipped", "delivered"}
