"""R3.10 generation key contract.

The V1 release contract:

- Generation seed derivation never includes the display column name.
  Same generation key + same strategy/config produces the same bytes
  regardless of what the column is called.

- Renaming a column does not shift generated output.

- Two columns with identical strategy/config produce identical output
  under the same key.

- Direct-YAML pipelines that need the pre-R3.10 column-name path can
  opt in by setting ``_legacy_column_name_seed: true`` on the column.

These tests are the engine-side acceptance gate. Companion platform
tests assert the admin setting + validation gates around it.
"""

from __future__ import annotations

from decoy_engine.context import make_key_resolver
from decoy_engine.generators.columns import ColumnGenerator
from decoy_engine.generators.derivation import (
    strategy_config_fingerprint,
    synthetic_column_seed,
)

_MASTER = bytes(range(32))


def _resolver(label: str = "demo-pipeline"):
    return make_key_resolver(_MASTER, label)


def _gen(config, *, derive_key=None, num_rows: int = 10, table: str = "t"):
    gen = ColumnGenerator(seed=42, derive_key=derive_key)
    return list(
        gen.generate_column(
            num_rows=num_rows,
            column_config=config,
            table_name=table,
            reference_data={},
        )
    )


# ── Fingerprint properties ───────────────────────────────────────────────────


def test_fingerprint_ignores_column_name():
    """The fingerprint is the seed-info label; renames must not shift it."""
    a = strategy_config_fingerprint(
        {"name": "first_name", "type": "faker", "faker_type": "first_name"}
    )
    b = strategy_config_fingerprint(
        {"name": "parent_first_name", "type": "faker", "faker_type": "first_name"}
    )
    assert a == b


def test_fingerprint_ignores_null_probability():
    """Null is a post-filter, not part of the strategy contract."""
    a = strategy_config_fingerprint({"name": "x", "type": "faker", "faker_type": "first_name"})
    b = strategy_config_fingerprint(
        {
            "name": "x",
            "type": "faker",
            "faker_type": "first_name",
            "null_probability": 0.1,
        }
    )
    assert a == b


def test_fingerprint_changes_when_strategy_config_changes():
    """Anything that actually affects output must change the fingerprint."""
    a = strategy_config_fingerprint({"type": "faker", "faker_type": "first_name"})
    b = strategy_config_fingerprint({"type": "faker", "faker_type": "last_name"})
    assert a != b


def test_fingerprint_is_key_order_stable():
    """Canonical JSON sorts keys; dict-iteration order must not leak."""
    a = strategy_config_fingerprint({"type": "faker", "faker_type": "first_name"})
    b = strategy_config_fingerprint({"faker_type": "first_name", "type": "faker"})
    assert a == b


# ── Column rename invariance ────────────────────────────────────────────────


def test_rename_does_not_change_keyed_output():
    """The headline R3.10 fix: renaming a column under the same key
    must produce identical generated bytes."""
    resolver = _resolver()
    base = {"name": "first_name", "type": "faker", "faker_type": "first_name"}
    renamed = {**base, "name": "given_name"}
    assert _gen(base, derive_key=resolver) == _gen(renamed, derive_key=resolver)


def test_rename_does_not_change_unkeyed_output():
    """Even without a master key, the unkeyed fallback must use the
    fingerprint, not the name, so renames are stable in CLI dev runs."""
    base = {"name": "first_name", "type": "faker", "faker_type": "first_name"}
    renamed = {**base, "name": "given_name"}
    assert _gen(base) == _gen(renamed)


def test_rename_for_categorical_does_not_change_output():
    base = {
        "name": "status",
        "type": "categorical",
        "categories": ["new", "shipped", "delivered"],
    }
    renamed = {**base, "name": "order_status"}
    resolver = _resolver()
    assert _gen(base, derive_key=resolver) == _gen(renamed, derive_key=resolver)


# ── Cross-column same-config equality ────────────────────────────────────────


def test_two_columns_same_config_produce_identical_output():
    """Two columns with identical strategy/config (different names)
    must produce the same generated values under the same key."""
    resolver = _resolver()
    a = {"name": "first_name", "type": "faker", "faker_type": "first_name"}
    b = {"name": "parent_first_name", "type": "faker", "faker_type": "first_name"}
    assert _gen(a, derive_key=resolver) == _gen(b, derive_key=resolver)


def test_different_faker_type_produces_different_output():
    """Sanity: when the strategy/config actually differs, output differs."""
    resolver = _resolver()
    first = {"name": "x", "type": "faker", "faker_type": "first_name"}
    last = {"name": "x", "type": "faker", "faker_type": "last_name"}
    assert _gen(first, derive_key=resolver) != _gen(last, derive_key=resolver)


# ── Key scope properties ─────────────────────────────────────────────────────


def test_same_master_same_label_reproduces():
    """Pipeline Key mode: same master + same label must reproduce."""
    config = {"name": "x", "type": "faker", "faker_type": "first_name"}
    assert _gen(config, derive_key=_resolver("p1")) == _gen(config, derive_key=_resolver("p1"))


def test_different_pipeline_label_shifts_output():
    """Changing the pipeline key changes generated output."""
    config = {"name": "x", "type": "faker", "faker_type": "first_name"}
    assert _gen(config, derive_key=_resolver("p1")) != _gen(config, derive_key=_resolver("p2"))


# ── Legacy column-name opt-in ────────────────────────────────────────────────


def test_legacy_column_name_seed_restores_pre_r3_10_coupling():
    """Direct-YAML compat path: when ``_legacy_column_name_seed`` is
    set, the column-name *does* feed into the seed, so renames shift
    output (the pre-R3.10 contract). This is the documented escape
    hatch for legacy CLI pipelines that rely on the old behavior."""
    resolver = _resolver()
    base = {
        "name": "first_name",
        "type": "faker",
        "faker_type": "first_name",
        "_legacy_column_name_seed": True,
    }
    renamed = {**base, "name": "given_name"}
    assert _gen(base, derive_key=resolver) != _gen(renamed, derive_key=resolver)


# ── synthetic_column_seed contract ───────────────────────────────────────────


def test_synthetic_column_seed_is_int_in_signed_int32_range():
    """Seed must fit in the 32-bit non-negative integer range that
    Faker.seed_instance and random.seed accept without wrapping."""
    seed = synthetic_column_seed(
        derive_key=_resolver(),
        column_config={"type": "faker", "faker_type": "first_name"},
        fallback_seed=42,
    )
    assert isinstance(seed, int)
    assert 0 <= seed < 2**32


def test_synthetic_column_seed_fresh_path_returns_fresh_bytes():
    """``determinism: fresh`` draws from os.urandom; two consecutive
    calls should almost certainly differ."""
    cfg = {"determinism": "fresh", "type": "faker", "faker_type": "first_name"}
    a = synthetic_column_seed(
        derive_key=_resolver(),
        column_config=cfg,
        fallback_seed=42,
    )
    b = synthetic_column_seed(
        derive_key=_resolver(),
        column_config=cfg,
        fallback_seed=42,
    )
    # 32-bit urandom collision probability is ~2^-32; this is safe.
    assert a != b
