"""Generate-side keyed determinism.

ColumnGenerator now accepts an optional ``derive_key`` callable. When set,
per-column seeds come from ``derive_key("col:<name>")[:4]`` so the same
key + same column always yield the same bytes — that's the property the
platform's pipeline-key UX relies on.

Without a key, behavior falls back to the legacy seed-based path so old
callers don't drift.
"""

from decoy_engine.context import ExecutionContext, make_key_resolver
from decoy_engine.generators.columns import ColumnGenerator
from decoy_engine.graph.ops import generate_op

_MASTER_A = bytes(range(32))
_MASTER_B = bytes(255 - b for b in range(32))


def _gen_column(derive_key, num_rows: int = 10):
    gen = ColumnGenerator(seed=42, derive_key=derive_key)
    return list(
        gen.generate_column(
            num_rows=num_rows,
            column_config={"name": "first_name", "type": "faker", "faker_type": "first_name"},
            table_name="t",
            reference_data={},
        )
    )


def test_same_key_same_column_yields_identical_bytes():
    resolver = make_key_resolver(_MASTER_A, "demo-pipeline")
    a = _gen_column(resolver)
    b = _gen_column(resolver)
    assert a == b, "same key on two ColumnGenerators must produce identical column"


def test_different_pipeline_label_changes_output():
    a = _gen_column(make_key_resolver(_MASTER_A, "pipeline-one"))
    b = _gen_column(make_key_resolver(_MASTER_A, "pipeline-two"))
    assert a != b, "different pipeline labels must shift generated bytes"


def test_different_master_changes_output():
    a = _gen_column(make_key_resolver(_MASTER_A, "demo-pipeline"))
    b = _gen_column(make_key_resolver(_MASTER_B, "demo-pipeline"))
    assert a != b, "different master keys must shift generated bytes"


def test_no_key_preserves_legacy_seed_behavior():
    # Two seed-only ColumnGenerators with the same seed must produce
    # identical output — regression guard for the unkeyed fallback.
    a = _gen_column(None)
    b = _gen_column(None)
    assert a == b, "same seed without key must produce identical output"


def test_keyed_and_unkeyed_diverge():
    # Sanity: the keyed path should produce different bytes than the
    # unkeyed seed-based path; otherwise the key isn't actually doing
    # anything.
    keyed = _gen_column(make_key_resolver(_MASTER_A, "demo-pipeline"))
    unkeyed = _gen_column(None)
    assert keyed != unkeyed


def test_generate_op_consumes_pipeline_derive_key_from_ctx():
    # End-to-end through the graph op: pipeline_derive_key on the
    # ExecutionContext must reach ColumnGenerator and shift output.
    cfg = {
        "row_count": 10,
        "columns": {"first_name": {"strategy": "faker", "faker_type": "first_name"}},
    }
    ctx_keyed = ExecutionContext(pipeline_derive_key=make_key_resolver(_MASTER_A, "alpha"))
    ctx_other = ExecutionContext(pipeline_derive_key=make_key_resolver(_MASTER_A, "beta"))
    ctx_unkeyed = ExecutionContext()  # no pipeline_derive_key

    a = list(generate_op.apply([], cfg, ctx_keyed)["first_name"])
    b = list(generate_op.apply([], cfg, ctx_keyed)["first_name"])
    c = list(generate_op.apply([], cfg, ctx_other)["first_name"])
    d = list(generate_op.apply([], cfg, ctx_unkeyed)["first_name"])

    assert a == b, "same context, same config → identical output"
    assert a != c, "different pipeline label → different output"
    assert a != d, "keyed vs unkeyed paths must differ"


def test_mask_derive_key_is_separate_from_pipeline_derive_key():
    # The two fields are independent: setting only `derive_key` (mask)
    # leaves the generate path unkeyed, and vice versa. This guards the
    # invariant the platform relies on — mask uses master, generate uses
    # pipeline, never crossed.
    ctx = ExecutionContext(derive_key=make_key_resolver(_MASTER_A, "instance"))
    assert ctx.pipeline_derive_key is None
    assert ctx.derive_key is not None

    ctx2 = ExecutionContext(pipeline_derive_key=make_key_resolver(_MASTER_A, "p1"))
    assert ctx2.derive_key is None
    assert ctx2.pipeline_derive_key is not None
